### DISCUSSION TITLE
v0.5.2

### DISCUSSION THREAD

**Discussion by wandeber** [wandeber/agnese#10] [Announcements]
Now you can use [JSON schemas](schemas) with VSCode to enable autocompletion and validation! 💪

#### JSON:

```json
{
  "$schema": "node_modules/agnese/schema/index.json",
  "value": {
    "type": "Integer",
    "fromPath": "characteristics.age"
  }
}
```

#### YAML:

You need to install the [YAML](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) extension.

```yaml
# yaml-language-server: $schema=node_modules/agnese/schema/index.json
type: Object
fields:
  - name: parent
    value:
      default: Son Goku
```

<hr /><em>This discussion was created from the release <a href='https://github.com/wandeber/agnese/releases/tag/v0.5.2'>v0.5.2</a>.</em>
