### DISCUSSION TITLE
v0.4.0

### DISCUSSION THREAD

**Discussion by wandeber** [wandeber/agnese#5] [Announcements]
Now preprocessors allows to define an array of arguments with all the same features as FieldValue: default, fromPath, quara... ^^ Things like:
```yaml
type: Integer
preprocessor:
  name: sum
  args:
    - fromPath: characteristics.height
    - default: 14
```

<hr /><em>This discussion was created from the release <a href='https://github.com/wandeber/agnese/releases/tag/v0.4.0'>v0.4.0</a>.</em>
